export const cars = [
  {
    brand: 'Audi',
    model: 'A1',
    img: 'audi-a1.jpg',
    price: 30000,
    description: 'Достойный авто по доступной цене. Приятный разгон и хорошая шумоизоляция.',
    color: 'grey',
    year: 2018,
    topSpeed: 193,
    weight: 1140,
    drive: 'front-wheel',
  },
  {
    brand: 'Audi',
    model: 'A8',
    img: 'audi-a8.jpg',
    price: 40000,
    description: 'Достойный авто по доступной цене. Приятный разгон и хорошая шумоизоляция.',
    color: 'black',
    year: 2020,
    topSpeed: 242,
    weight: 1190,
    drive: 'four-wheel',
  },
  {
    brand: 'Audi',
    model: 'Q7',
    img: 'audi-q7.jpg',
    price: 60000,
    description: 'Достойный авто по доступной цене. Приятный разгон и хорошая шумоизоляция.',
    color: 'black',
    year: 2020,
    topSpeed: 216,
    weight: 2445,
    drive: 'four-wheel',
  },
  {
    brand: 'BMW',
    model: 'e60',
    img: 'bmw-e60.jpg',
    price: 50000,
    description: 'Достойный авто по доступной цене. Приятный разгон и хорошая шумоизоляция.',
    color: 'black',
    year: 2005,
    topSpeed: 192,
    weight: 1830,
    drive: 'four-wheel',
  },
  {
    brand: 'BMW',
    model: 'x5',
    img: 'bmw-x5.jpg',
    price: 40000,
    description: 'Достойный авто по доступной цене. Приятный разгон и хорошая шумоизоляция.',
    color: 'white',
    year: 2018,
    topSpeed: 250,
    weight: 2250,
    drive: 'four-wheel',
  },
  {
    brand: 'Mitsubishi',
    model: 'Pajero',
    img: 'mitsu-pajero.jpg',
    price: 35000,
    description: 'Достойный авто по доступной цене. Приятный разгон и хорошая шумоизоляция.',
    color: 'white',
    year: 2003,
    topSpeed: 197,
    weight: 2165,
    drive: 'rear-wheel',
  },
  {
    brand: 'Mitsubishi',
    model: 'Lancer',
    img: 'mitsu-lancer.jpg',
    price: 50000,
    description: 'Достойный авто по доступной цене. Приятный разгон и хорошая шумоизоляция.',
    color: 'white',
    year: 2015,
    topSpeed: 197,
    weight: 2165,
    drive: 'rear-wheel',
  },
  {
    brand: 'Skoda',
    model: 'Fabia',
    img: 'skoda-fabia.jpg',
    price: 40000,
    description: 'Достойный авто по доступной цене. Приятный разгон и хорошая шумоизоляция.',
    color: 'green',
    year: 2005,
    topSpeed: 197,
    weight: 2165,
    drive: 'rear-wheel',
  },
  {
    brand: 'Skoda',
    model: 'Octavia',
    img: 'skoda-octavia.jpg',
    price: 30000,
    description: 'Достойный авто по доступной цене. Приятный разгон и хорошая шумоизоляция.',
    color: 'red',
    year: 2015,
    topSpeed: 197,
    weight: 2165,
    drive: 'rear-wheel',
  },
  {
    brand: 'Volvo',
    model: 'S60',
    img: 'volvo-s60.jpg',
    price: 45000,
    description: 'Достойный авто по доступной цене. Приятный разгон и хорошая шумоизоляция.',
    color: 'red',
    year: 2017,
    topSpeed: 197,
    weight: 2165,
    drive: 'rear-wheel',
  },
  {
    brand: 'Volvo',
    model: 'XC90',
    img: 'volvo-xc90.jpg',
    price: 60000,
    description: 'Достойный авто по доступной цене. Приятный разгон и хорошая шумоизоляция.',
    color: 'black',
    year: 2020,
    topSpeed: 197,
    weight: 2165,
    drive: 'rear-wheel',
  },
];

export const brands = Array.from(new Set(cars.map(car => car.brand)));