const cars = [
  {
    id: 1,
    brand: 'Audi',
    model: 'A1',
    img: 'audi-a1.jpeg',
    price: 30000,
    description: 'Достойный авто по доступной цене. Приятный разгон и хорошая шумоизоляция.',
  },
  {
    id: 2,
    brand: 'Audi',
    model: 'A8',
    img: 'audi-a8.jpeg',
    price: 40000,
    description: 'Достойный авто по доступной цене. Приятный разгон и хорошая шумоизоляция.',
  },
  {
    id: 3,
    brand: 'Audi',
    model: 'Q7',
    img: 'audi-q7.jpeg',
    price: 60000,
    description: 'Достойный авто по доступной цене. Приятный разгон и хорошая шумоизоляция.',
  },
  {
    id: 4,
    brand: 'BMW',
    model: 'e60',
    img: 'bmw-e60.jpg',
    price: 50000,
    description: 'Достойный авто по доступной цене. Приятный разгон и хорошая шумоизоляция.',
  },
  {
    id: 5,
    brand: 'BMW',
    model: 'x5',
    img: 'bmw-x5.jpg',
    price: 40000,
    description: 'Достойный авто по доступной цене. Приятный разгон и хорошая шумоизоляция.',
  },
  {
    id: 6,
    brand: 'Skoda',
    model: 'Fabia',
    img: 'skoda-fabia.jpeg',
    price: 40000,
    description: 'Достойный авто по доступной цене. Приятный разгон и хорошая шумоизоляция.',
  },
  {
    id: 7,
    brand: 'Skoda',
    model: 'Octavia',
    img: 'skoda-octavia.jpeg',
    price: 30000,
    description: 'Достойный авто по доступной цене. Приятный разгон и хорошая шумоизоляция.',
  },
];
